# Generated by targets::tar_renv(): do not edit by hand
library(MonoPhy)
library(RColorBrewer)
library(ape)
library(caper)
library(effectsize)
library(fs)
library(ggimage)
library(ggnewscale)
library(ggplot2)
library(ggrepel)
library(ggtree)
library(ggtreeExtra)
library(glue)
library(gt)
library(gtExtras)
library(janitor)
library(nlme)
library(patchwork)
library(phytools)
library(rnaturalearth)
library(rnaturalearthdata)
library(scales)
library(sf)
library(tidytree)
library(tidyverse)
library(treeio)
library(vegan)
library(vroom)
library(webshot2)
